services:
  app:
    image: fijoromeis/emobook-backend:latest
    container_name: emotion-app-backend
    volumes:
      - model-cache:/root/.cache/huggingface
    ports:
      - "8000:8000"

  db:
    image: postgres:15
    container_name: emotion-app-db
    environment:
      POSTGRES_DB: emotiondb
      POSTGRES_USER: emotionuser
      POSTGRES_PASSWORD: supersecure
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d

volumes:
  db-data:
  model-cache:
