services:
  app:
    image: fijoromeis/emobook-backend:latest
    container_name: emotion-app-backend
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: emotiondb
      DB_USER: emotionuser
      DB_PASS: supersecure
    depends_on:
      - db
    command: >
      sh -c "python3 db_insert.py && uvicorn main:app --host 0.0.0.0 --port 8000"
    ports:
      - "8000:8000"
    volumes:
      - model-cache:/root/.cache/huggingface

  db:
    image: postgres:15
    container_name: emotion-app-db
    environment:
      POSTGRES_DB: emotiondb
      POSTGRES_USER: emotionuser
      POSTGRES_PASSWORD: supersecure
    ports:
      - "5432:5432"
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d

volumes:
  model-cache:
