name: Run docker-compose with ngrok

on:
  workflow_dispatch:

jobs:
  run-compose:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Docker Hub Login (für private Images)
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      # Docker Compose installieren
      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install docker-compose -y

      # docker-compose hochfahren
      - name: Start docker-compose
        run: |
          docker-compose up -d
          docker ps

      # Warte, bis die App erreichbar ist
      - name: Wait for app to be ready
        run: |
          for i in {1..30}; do
            if curl --silent --fail http://localhost:8000/ >/dev/null; then
              echo "App ist erreichbar!"
              exit 0
            fi
            echo "Warte auf App... ($i/30)"
            sleep 3
          done
          echo "App hat sich nicht gestartet!"
          docker-compose logs
          exit 1

      # ngrok installieren
      - name: Install ngrok
        run: |
          curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null
          echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | sudo tee /etc/apt/sources.list.d/ngrok.list
          sudo apt update && sudo apt install ngrok

      # ngrok authentifizieren
      - name: Authenticate ngrok
        run: ngrok config add-authtoken ${{ secrets.NGROK_AUTH_TOKEN }}

      # Tunnel auf Port 8000 starten (App läuft dort)
      - name: Start ngrok tunnel
        run: |
          nohup ngrok http 8000 > /dev/null &
          sleep 5
          echo "Öffentliche URL:"
          curl --silent --show-error --fail http://127.0.0.1:4040/api/tunnels | jq -r '.tunnels[0].public_url'

      # Container am Leben halten
      - name: Keep container alive
        run: |
          echo "docker-compose läuft jetzt für 6 Stunden..."
          sleep 21600
